const OSC_COLOR = "#66fcf1";
const OSC_RADIUS = 15;
const ROUND_HURDLE_RANDOM_RADIUS = 20;
const ROUND_HURDLE_RADIUS_MIN = 50;
const HURDLE_START_POINT = 20;
const OSC_FORCE = 5;
const POINT = 10;
const GAME_SPEED = 7;
