const OSC_COLOR = "#66fcf1";
const OSC_RADIUS = 15;
const OSC_FORCE = 5;
const RADIUS_MAX_RANDOM_VALUE = 20;
const RADIUS_MIN_VALUE = 50;
const HURDLE_START_POINT = 20;
const POINT = 10;
const GAME_SPEED = 8;
const GAME_STATE = {
    'MENU': 0,
    'RUNNING': 1,
    'OVER': 2,
};
const HURDLE_TYPE = {
    ROUND: 1,
    FLAT: 2
};
const NO_OF_HURDLE = 2;
const FLAT_HURDLE_MAX_WIDTH = 200;
const FLAT_HURDLE_HEIGHT = 50;


export {
    OSC_COLOR,
    OSC_RADIUS,
    OSC_FORCE,
    RADIUS_MAX_RANDOM_VALUE,
    RADIUS_MIN_VALUE,
    HURDLE_START_POINT,
    GAME_SPEED,
    POINT,
    GAME_STATE,
    HURDLE_TYPE,
    NO_OF_HURDLE,
    FLAT_HURDLE_MAX_WIDTH,
    FLAT_HURDLE_HEIGHT
};